<?php

/**
 * Implements hook_theme().
 */
function pcp_theme($existing, $type, $theme, $path) {
  return array(
    'pcp_template' => array(
      'variables' => array('uid' => NULL, 'completed' => NULL, 'incomplete' => NULL, 'total' => NULL, 'open_link' => NULL, 'hide_pcp_block' => NULL, 'nextfield_name' => NULL, 'nextfield_title' => NULL, 'current_percent' => NULL, 'next_percent' => NULL),
  	),
  );
}
